# Travis CI Configuration

language: node_js
node_js:
  - "7"
  - "6"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - librsvg2-dev
env:
  - CXX=g++-4.8
before_script:
  - ./node_modules/brunch/bin/brunch build
script:
  - npm run lint
  - npm test
