# Travis CI Configuration

language: node_js
node_js:
  - "8"
  - "7"
  - "6"
# Installing rsvg-brunch requires a C++11 compiler and librsvg
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - librsvg2-dev
env:
  - CXX=g++-4.8
install:
  - npm install
  - npm install coveralls
before_script:
  - brunch build --production
script:
  - npm run lint
  - npm run coverage
after_success:
  - cat coverage/lcov.info | coveralls
